record:
  # I would recommend excluding any object generated via listening from storage objects from storage
  # since they can usually be computed
  storageExclusionPrefixes:
    - deepstream_search/

storage:
  name: mongodb
  options:
    connectionString: ${MONGO_URL}
    database: ${MONGO_DATABASE}
    splitChar: /